import {isRangedWeapon,usesMags} from './gearCatalog.js'

export const ATTRIBUTES = ['brawn','nerves','smooth','focus','crime']
export const SKILLS = ['endure','fight','force','stunt','cool','drive','shoot','survival','flirt','leadership','speech','style','detect','fix','heal','know','awareness','dexterity','stealth','streetwise']
export function groupFeatIds(ids=[]){return ids.reduce((groups,id)=>{const existing=groups.find(group=>group.id===id);if(existing)existing.count++;else groups.push({id,count:1});return groups},[])}
export class RuleError extends Error { constructor(message) { super(message); this.name = 'RuleError' } }
const clone = value => structuredClone(value)
export function baseHero() {
  return { meta:{version:1}, personal:{name:'',job:'',age:'Adult',catchphrase:'',flaw:'',portraitDataUrl:null}, role:null,trope:null,tropeAttribute:null,
    attributes:Object.fromEntries(ATTRIBUTES.map(k=>[k,2])), skills:Object.fromEntries(SKILLS.map(k=>[k,1])), freeSkillPoints:[], feats:[],
    gear:{guns:[],items:[],storage:[],ride:null}, resources:{adrenaline:1,spotlight:1,cash:1,lethalBullets:1,grit:12}, experiences:[],mission:'' }
}
export function roleAttributeOptions(role){return role?.attributeChoices||role?.attributes||[role?.attribute].filter(Boolean)}
export function applyRole(hero, role, id = role.id, chosenAttr = role.attribute) { const h=clone(hero); if(!role) throw new RuleError('Unknown role'); const options=roleAttributeOptions(role),fixed=role.fixedAttributes||[],chosen=Array.isArray(chosenAttr)?chosenAttr:[chosenAttr].filter(Boolean),points=role.attributePoints??1,raised=[...fixed];for(const attribute of chosen)if(!raised.includes(attribute)&&options.includes(attribute)&&raised.length<points)raised.push(attribute);if(raised.length!==points)throw new RuleError('Wrong number of Role attributes');h.roleAttribute=raised[0]||null;h.roleAttributes=raised;for(const attribute of raised)h.attributes[attribute]++;h.role=id;for(const s of role.skills||[])h.skills[s]++;if(role.superpower){h.superpower=clone(role.superpower);h.resources.power=1}return h }
export function applyProdigyRole(hero,trope,role,id,chosenAttr){const h=applyTrope(hero,trope,chosenAttr,trope.id);h.role=id;h.roleTrope=trope.id;h.roleAttribute=chosenAttr;h.roleAttributes=[chosenAttr];h.trope=null;h.tropeAttribute=null;if(role.superpower){h.superpower=clone(role.superpower);h.resources.power=1}return h}
export function tropeAttributeOptions(hero,trope) { const options=trope.attributes.filter(a=>hero.attributes[a]<3); return options.length ? options : trope.attributes }
export function applyTrope(hero,trope,chosenAttr,id=trope.id) { const allowed=tropeAttributeOptions(hero,trope); if(!allowed.includes(chosenAttr)) throw new RuleError(`Illegal trope attribute: ${chosenAttr}`); const h=clone(hero); h.trope=id; h.tropeAttribute=chosenAttr; h.attributes[chosenAttr]++; for(const s of trope.skills) h.skills[s]++; return h }
export const freeSkillTargets = hero => SKILLS.filter(s=>hero.skills[s]<3)
export function applyFreeSkillPoints(hero,points,count=2) { if(points.length!==count) throw new RuleError(`Exactly ${count} free Skill points are required`); const h=clone(hero); for(const s of points){ if(!SKILLS.includes(s)||h.skills[s]>=3) throw new RuleError(`Illegal free Skill point: ${s}`); h.skills[s]++; } h.freeSkillPoints=[...points]; return h }
export function applyAge(hero,age) { if(!['Young','Adult','Old'].includes(age)) throw new RuleError('Invalid age'); const h=clone(hero); h.personal.age=age; h.resources.adrenaline=age==='Young'?2:1; h.resources.lethalBullets=age==='Old'?2:1; return h }
export function featSlots(hero,role={}) { if(role.actsAsTrope)return {role:role.featCount||3,trope:0,extra:0,forced:role.forcedFeats||[]};if(role.extraTrope||role.doubleTrope)return {role:role.roleFeatCount||1,trope:role.tropeFeatCount||1,extra:role.extraFeatCount||0,forced:role.forcedFeats||[]};const age=hero.personal.age; return age==='Young'?{role:1,trope:1,extra:0,forced:['too_young_to_die']}:{role:2,trope:1,extra:age==='Old'?1:0,forced:[]} }
export function applyFeats(hero,selections,role,trope,featCatalog={}) { const h=clone(hero), slots=featSlots(h,role); const roleIds=selections.role||[], tropeIds=selections.trope||[], extra=selections.extra||[]; if(roleIds.length!==slots.role||tropeIds.length!==slots.trope||extra.length!==slots.extra) throw new RuleError('Wrong number of feats'); if(role&&roleIds.some(x=>!role.feats.includes(x))) throw new RuleError('Role feat not permitted'); if(trope&&tropeIds.some(x=>!trope.feats.includes(x))) throw new RuleError('Trope feat not permitted'); if(role?.extraFeatPool!=='all'&&extra.some(x=>!role.feats.includes(x)&&!trope?.feats.includes(x))) throw new RuleError('Extra feat not permitted');if(extra.some(x=>!featCatalog[x]))throw new RuleError('Unknown extra feat'); const all=[...roleIds,...tropeIds,...extra,...slots.forced],counts=Object.fromEntries(all.map(id=>[id,all.filter(value=>value===id).length])); for(const [id,count] of Object.entries(counts)){const feat=featCatalog[id]||{},limit=feat.repeatable?(feat.maxRanks||Infinity):1;if(count>limit)throw new RuleError('Duplicate feat')} h.feats=all; return h }
function classify(item,gear) { const record=gear.gear?.[item]||gear.weapons?.[item]||gear.items?.[item]||gear.guns?.[item]||gear.rides?.[item]; if(!record) throw new RuleError(`Unknown gear: ${item}`); return {id:item,...record} }
export function resolveGear(hero,entries,gear) { const h=clone(hero); h.gear={guns:[],items:[],storage:[],ride:null}; for(const id of entries){ const x=classify(id,gear); if(isRangedWeapon(x)) h.gear.guns.push({...x,...(usesMags(x)?{mags:2}:{})}); else if(x.speed!=null) h.gear.ride={...x}; else h.gear.items.push({...x,bag:!!x.bag}) } return h }
export function finalize(hero,data) { const h=clone(hero),ids=h.feats.map(x=>x.split('__').at(-1)); if(ids.includes('cash_flow'))h.resources.cash=3;if(ids.includes('moneybags'))h.resources.cash=4;if(ids.includes('unlimited_funds'))h.resources.cash=5;h.meta.version=1;return h }
