export const ATTRIBUTES = ['brawn','nerves','smooth','focus','crime']
export const SKILLS = ['endure','fight','force','stunt','cool','drive','shoot','survival','flirt','leadership','speech','style','detect','fix','heal','know','awareness','dexterity','stealth','streetwise']
export class RuleError extends Error { constructor(message) { super(message); this.name = 'RuleError' } }
const clone = value => structuredClone(value)
export function baseHero() {
  return { meta:{version:1}, personal:{name:'',job:'',age:'Adult',catchphrase:'',flaw:'',portraitDataUrl:null}, role:null,trope:null,tropeAttribute:null,
    attributes:Object.fromEntries(ATTRIBUTES.map(k=>[k,2])), skills:Object.fromEntries(SKILLS.map(k=>[k,1])), freeSkillPoints:[], feats:[],
    gear:{guns:[],items:[],storage:[],ride:null}, resources:{adrenaline:1,spotlight:1,cash:1,lethalBullets:1,grit:12}, experiences:[],mission:'' }
}
export function roleAttributeOptions(role){return role?.attributeChoices||role?.attributes||[role?.attribute].filter(Boolean)}
export function applyRole(hero, role, id = role.id, chosenAttr = role.attribute) { const h=clone(hero); if(!role) throw new RuleError('Unknown role'); const options=roleAttributeOptions(role);if(!options.includes(chosenAttr))throw new RuleError(`Illegal Role attribute: ${chosenAttr}`);h.role=id;h.roleAttribute=chosenAttr;h.attributes[chosenAttr]++;for(const s of role.skills)h.skills[s]++;if(role.superpower){h.superpower=clone(role.superpower);h.resources.power=1}return h }
export function tropeAttributeOptions(hero,trope) { const options=trope.attributes.filter(a=>hero.attributes[a]<3); return options.length ? options : trope.attributes }
export function applyTrope(hero,trope,chosenAttr,id=trope.id) { const allowed=tropeAttributeOptions(hero,trope); if(!allowed.includes(chosenAttr)) throw new RuleError(`Illegal trope attribute: ${chosenAttr}`); const h=clone(hero); h.trope=id; h.tropeAttribute=chosenAttr; h.attributes[chosenAttr]++; for(const s of trope.skills) h.skills[s]++; return h }
export const freeSkillTargets = hero => SKILLS.filter(s=>hero.skills[s]<3)
export function applyFreeSkillPoints(hero,points) { if(points.length!==2) throw new RuleError('Exactly two free Skill points are required'); const h=clone(hero); for(const s of points){ if(!SKILLS.includes(s)||h.skills[s]>=3) throw new RuleError(`Illegal free Skill point: ${s}`); h.skills[s]++; } h.freeSkillPoints=[...points]; return h }
export function applyAge(hero,age) { if(!['Young','Adult','Old'].includes(age)) throw new RuleError('Invalid age'); const h=clone(hero); h.personal.age=age; h.resources.adrenaline=age==='Young'?2:1; h.resources.lethalBullets=age==='Old'?2:1; return h }
export function featSlots(hero) { const age=hero.personal.age; return age==='Young'?{role:1,trope:1,extra:0,forced:['too_young_to_die']}:{role:2,trope:1,extra:age==='Old'?1:0,forced:[]} }
export function applyFeats(hero,selections,role,trope) { const h=clone(hero), slots=featSlots(h); const roleIds=selections.role||[], tropeIds=selections.trope||[], extra=selections.extra||[]; if(roleIds.length!==slots.role||tropeIds.length!==slots.trope||extra.length!==slots.extra) throw new RuleError('Wrong number of feats'); if(role&&roleIds.some(x=>!role.feats.includes(x))) throw new RuleError('Role feat not permitted'); if(trope&&tropeIds.some(x=>!trope.feats.includes(x))) throw new RuleError('Trope feat not permitted'); if(extra.some(x=>!role.feats.includes(x)&&!trope.feats.includes(x))) throw new RuleError('Extra feat not permitted'); const all=[...roleIds,...tropeIds,...extra,...slots.forced]; if(new Set(all).size!==all.length) throw new RuleError('Duplicate feat'); h.feats=all; return h }
function classify(item,gear) { const record=gear.items?.[item]||gear.guns?.[item]||gear.rides?.[item]; if(!record) throw new RuleError(`Unknown gear: ${item}`); return {id:item,...record} }
export function resolveGear(hero,entries,gear) { const h=clone(hero); h.gear={guns:[],items:[],storage:[],ride:null}; for(const id of entries){ const x=classify(id,gear); if(x.range) h.gear.guns.push({...x,mags:2}); else if(x.speed!=null) h.gear.ride={...x}; else h.gear.items.push({...x,bag:!!x.bag}) } return h }
export function finalize(hero,data) { const h=clone(hero),ids=h.feats.map(x=>x.split('__').at(-1)); if(ids.includes('cash_flow'))h.resources.cash=3;if(ids.includes('moneybags'))h.resources.cash=4;if(ids.includes('unlimited_funds'))h.resources.cash=5;h.meta.version=1;return h }
