import React,{useMemo,useState} from 'react'
import {makeRng} from '../../engine/dice.js'
import {generateRandom} from '../../engine/hero.js'
import {roleAttributeOptions} from '../../engine/build.js'
import HeroSheet from './HeroSheet.jsx'

const STEPS=['Role','Personal Data','Trope','Free Points','Feats','Gear','Review']
export default function GuidedHero({data,onBack,defaults={}}){
  const [step,setStep]=useState(defaults.role?1:0),[form,setForm]=useState({role:defaults.role||Object.keys(data.roles.roles)[0],trope:defaults.trope||Object.keys(data.tropes.tropes)[0],roleAttribute:null,tropeAttribute:null,age:'Adult',name:'',job:'',catchphrase:'',flaw:'',freeSkillPoints:[],roleFeats:[],tropeFeats:[],extraFeats:[],gearChoices:[],...defaults})
  const role=data.roles.roles[form.role],trope=data.tropes.tropes[form.trope],roleAttrs=roleAttributeOptions(role),roleAttr=roleAttrs.includes(form.roleAttribute)?form.roleAttribute:roleAttrs[0],legalTropeAttrs=trope.attributes.filter(a=>a!==roleAttr),tropeAttr=legalTropeAttrs.includes(form.tropeAttribute)?form.tropeAttribute:legalTropeAttrs[0]||trope.attributes[0],roleCap=form.age==='Young'?1:2
  const pins={...form,roleAttribute:roleAttr,tropeAttribute:tropeAttr};if(form.freeSkillPoints.length!==2)delete pins.freeSkillPoints;if(form.roleFeats.length!==roleCap)delete pins.roleFeats;if(form.tropeFeats.length!==1)delete pins.tropeFeats;if(form.extraFeats.length!==(form.age==='Old'?1:0))delete pins.extraFeats
  const hero=useMemo(()=>{try{return generateRandom(makeRng(73),data,pins)}catch{return null}},[data,JSON.stringify(pins)])
  const set=(key,value)=>setForm(current=>({...current,[key]:value}))
  if(step===6&&hero)return <HeroSheet hero={hero} data={data} onHome={onBack}/>
  const canContinue=!(step===3&&form.freeSkillPoints.length!==2)&&!(step===4&&(form.roleFeats.length!==roleCap||form.tropeFeats.length!==1||(form.age==='Old'&&form.extraFeats.length!==1)))
  return <main className="panel wizard"><button className="link" onClick={step?()=>setStep(step-1):onBack}>← Back</button><div className="progress"><i style={{width:`${(step+1)/7*100}%`}}/></div><p className="eyebrow">STEP {step+1} / 7</p><h1>{STEPS[step]}</h1>
    {step===0&&<><ChoiceGrid values={data.roles.roles} selected={form.role} onChange={value=>setForm(current=>({...current,role:value,roleAttribute:null,roleFeats:[],gearChoices:[]}))}/>{roleAttrs.length>1&&<><h2>Role Attribute</h2><div className="choices">{roleAttrs.map(a=><button key={a} className={roleAttr===a?'selected':''} onClick={()=>set('roleAttribute',a)}>{a}</button>)}</div></>}</>}
    {step===1&&<div className="form-grid"><label>Name<input value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>Age<select value={form.age} onChange={e=>set('age',e.target.value)}><option>Young</option><option>Adult</option><option>Old</option></select></label><label>{role.origins?'Origin':'Job'}<input value={form.job} placeholder={(role.jobs||role.origins||[''])[0]} onChange={e=>set('job',e.target.value)}/></label><label>Catchphrase<input value={form.catchphrase} placeholder={role.catchphrases?.[0]||''} onChange={e=>set('catchphrase',e.target.value)}/></label><label>Flaw<input value={form.flaw} placeholder={role.flaws?.[0]||''} onChange={e=>set('flaw',e.target.value)}/></label></div>}
    {step===2&&<><ChoiceGrid values={data.tropes.tropes} selected={form.trope} onChange={value=>setForm(current=>({...current,trope:value,tropeAttribute:null,tropeFeats:[],extraFeats:[]}))}/><h2>Raised Attribute</h2><div className="choices">{trope.attributes.map(a=><button disabled={a===roleAttr} className={tropeAttr===a?'selected':''} onClick={()=>set('tropeAttribute',a)} key={a}>{a}{a===roleAttr?' (already raised by Role)':''}</button>)}</div></>}
    {step===3&&<FreeSkills form={form} role={role} trope={trope} hero={hero} set={set}/>} 
    {step===4&&<><p>{form.age==='Young'?'Choose one Role Feat and one Trope Feat; Too Young to Die is automatic.':form.age==='Old'?'Choose two Role Feats, one Trope Feat, and one extra.':'Choose two Role Feats and one Trope Feat.'}</p><FeatPicker title={`Role feats (${form.roleFeats.length}/${roleCap})`} ids={role.feats} chosen={form.roleFeats} cap={roleCap} data={data} onChange={value=>set('roleFeats',value)}/><FeatPicker title="Trope feat (1)" ids={trope.feats} chosen={form.tropeFeats} cap={1} data={data} onChange={value=>set('tropeFeats',value)}/>{form.age==='Old'&&<FeatPicker title="Extra feat (1)" ids={[...new Set([...role.feats,...trope.feats])].filter(id=>![...form.roleFeats,...form.tropeFeats].includes(id))} chosen={form.extraFeats} cap={1} data={data} onChange={value=>set('extraFeats',value)}/>}</>}
    {step===5&&<><p>Choose the offered starting gear. Every gun begins with 2 Mags.</p>{(role.gear||[]).map((spec,index)=><GearChoice key={index} index={index} spec={spec} data={data} value={form.gearChoices[index]} onChange={value=>{const next=[...form.gearChoices];next[index]=value;set('gearChoices',next)}}/>)}{hero&&<ul>{[...hero.gear.guns,...hero.gear.items].map(x=><li key={x.id}>{x.name}</li>)}</ul>}</>}
    <button className="primary" disabled={!canContinue} onClick={()=>setStep(step+1)}>{step===5?'REVIEW HERO':'CONTINUE'}</button>
  </main>
}
function ChoiceGrid({values,selected,onChange}){return <div className="card-grid">{Object.entries(values).map(([id,value])=><button key={id} className={`choice-card ${id===selected?'selected':''}`} onClick={()=>onChange(id)}><strong>{value.name}</strong><small>{value.tagline||value.blurb}</small>{value.packName&&<small>{value.packName}</small>}</button>)}</div>}
function FreeSkills({form,role,trope,hero,set}){return <><p>Choose exactly two. A Skill cannot exceed 3.</p><div className="card-grid">{Object.keys(hero?.skills||{}).map(skill=>{const picked=form.freeSkillPoints.filter(x=>x===skill).length,base=1+(role.skills.includes(skill)?1:0)+(trope.skills.includes(skill)?1:0),disabled=form.freeSkillPoints.length>=2||base+picked>=3;return <button key={skill} disabled={disabled&&!picked} className={picked?'selected':''} onClick={()=>set('freeSkillPoints',picked?form.freeSkillPoints.filter((x,index)=>x!==skill||index!==form.freeSkillPoints.lastIndexOf(skill)):[...form.freeSkillPoints,skill])}>{skill} {base+picked}/3</button>})}</div><strong>{2-form.freeSkillPoints.length} points remaining</strong></>}
function FeatPicker({title,ids,chosen,cap,data,onChange}){return <section><h2>{title}</h2><div className="choices">{ids.map(id=><button key={id} disabled={!chosen.includes(id)&&chosen.length>=cap} className={chosen.includes(id)?'selected':''} onClick={()=>onChange(chosen.includes(id)?chosen.filter(x=>x!==id):[...chosen,id])}>{data.feats.feats[id]?.name||id}</button>)}</div></section>}
function GearChoice({index,spec,data,value,onChange}){let ids=[];const all=[...Object.entries(data.gear.items),...Object.entries(data.gear.guns)];if(Array.isArray(spec.choice))ids=spec.choice;else if(spec.choice==='any_gun')ids=Object.keys(data.gear.guns);else if(spec.choice==='any_weapon')ids=[...Object.keys(data.gear.guns),...Object.entries(data.gear.items).filter(([,x])=>x.kind==='melee').map(([id])=>id)];else if(spec.choice==='any_1cash_item')ids=all.filter(([,x])=>x.cost===1).map(([id])=>id);else if(spec.choice==='any_2cash_item')ids=all.filter(([,x])=>x.cost===2).map(([id])=>id);else if(spec.choice==='any_precious_item'||spec.choice==='precious_item')ids=Object.entries(data.gear.items).filter(([,x])=>x.precious||x.cost>=3).map(([id])=>id);else if(spec.choice==='any_item')ids=all.map(([id])=>id);else if(spec.ride)ids=Object.entries(data.gear.rides).filter(([,x])=>x.speed===spec.ride.speed).map(([id])=>id);if(!ids.length){const budget=typeof spec.choice==='string'&&spec.choice.match(/^any_(\d+)cash_items$/);return budget?<p>Choice {index+1}: {budget[1]} Cash worth of items (selected automatically).</p>:null}return <label>Choice {index+1}<select value={value||''} onChange={e=>onChange(e.target.value)}><option value="">Random legal choice</option>{ids.map(id=><option key={id} value={id}>{data.gear.gear[id]?.name||id}</option>)}</select></label>}
