import React,{useEffect,useMemo,useRef,useState} from 'react'
import drawHeroSheet from '../../pdf/heroSheet.js'
import {actionSuccessProbability,CONDITION_EFFECTS,conditionPenalty,DIFFICULTIES,rollAction} from '../../engine/actionRoll.js'
import {heroMarkdown} from '../../engine/heroMarkdown.js'
import {groupFeatIds} from '../../engine/build.js'
import {isMeleeWeapon,isRangedWeapon,usesMags,weaponModifier} from '../../engine/gearCatalog.js'
import { availableTropes } from '../../engine/tropes.js'
import {Banner,Button,Dots,Section,Tracker} from '../components/index.jsx'
import {catalogDescription} from '../catalogDescription.js'
import {describeJob} from '../jobDescriptions.js'
import {styles,theme} from '../theme.js'

const ATTRIBUTE_SKILLS={brawn:['endure','fight','force','stunt'],nerves:['cool','drive','shoot','survival'],smooth:['flirt','leadership','speech','style'],focus:['detect','fix','heal','know'],crime:['awareness','dexterity','stealth','streetwise']}
const CONDITIONS=['Hurt','Nervous','Like a Fool','Distracted','Scared','Tired','Broken']
const RANGES=['melee','close','medium','long']
const AGE_DESCRIPTIONS={Young:'A young up-and-comer with 2 starting Adrenaline and Too Young to Die.',Adult:'An experienced Hero in their prime, with standard starting Feats and resources.',Old:'A seasoned veteran with an extra Feat and 2 starting Lethal Bullets.'}
const display=(value,fallback='—')=>value==null||value===''?fallback:typeof value==='string'||typeof value==='number'?String(value):value.name||value.id||fallback
const catalogItem=(item,data)=>item?.id&&data?.gear?.gear?.[item.id]||item
const savedWeaponType=(item,data)=>isRangedWeapon(item)||isRangedWeapon(catalogItem(item,data))?'ranged':isMeleeWeapon(item)||isMeleeWeapon(catalogItem(item,data))?'melee':null
const groupBy=(values,key)=>values.reduce((groups,value)=>{const group=key(value);(groups[group]??=[]).push(value);return groups},{})
function record(data,collection,value){const id=typeof value==='string'?value:value?.id,group=data?.[collection]||{},source=group[collection]||group.gear||group;return source[id]||value||{}}
const nameOf=(data,collection,value)=>display(record(data,collection,value).name,display(value).replace(/[_-]+/g,' '))
function encodedHero(hero){if(typeof btoa!=='function')return '';return btoa(unescape(encodeURIComponent(JSON.stringify(hero)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}

function EditValue({value,field,editable,onEdit,onReroll}){const [draft,setDraft]=useState(()=>display(value,''));useEffect(()=>setDraft(display(value,'')),[value]);if(editable)return <span className="inline-editor"><input value={draft} aria-label={`Edit ${field}`} onChange={event=>setDraft(event.target.value)} onBlur={()=>onEdit?.(field,draft)} onKeyDown={event=>{if(event.key==='Enter')event.currentTarget.blur();if(event.key==='Escape'){setDraft(display(value,''));event.currentTarget.blur()}}}/>{onReroll&&<button type="button" onClick={()=>onReroll(field)} aria-label={`Reroll ${field}`} style={iconButton}>↻</button>}</span>;return <span style={{display:'inline-flex',alignItems:'center',gap:5,minWidth:0}}><span style={{overflow:'hidden',textOverflow:'ellipsis'}}>{display(value)}</span>{onReroll&&<button type="button" onClick={()=>onReroll(field)} aria-label={`Reroll ${field}`} style={iconButton}>↻</button>}</span>}
function EditSelect({value,field,options,onEdit,onReroll}){const groups=groupBy(options,option=>option.source||'');return <span className="inline-editor"><select value={value||''} aria-label={`Edit ${field}`} onChange={event=>onEdit?.(field,event.target.value)}>{Object.entries(groups).map(([source,values])=>source?<optgroup key={source} label={source}>{values.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</optgroup>:values.map(option=><option key={option.id||option} value={option.id||option}>{option.name||option}</option>))}</select>{onReroll&&<button type="button" onClick={()=>onReroll(field)} aria-label={`Reroll ${field}`} style={iconButton}>↻</button>}</span>}
const iconButton={appearance:'none',background:'transparent',border:0,color:theme.colors.red,cursor:'pointer',fontSize:17,lineHeight:1,padding:0}

export default function HeroSheet({hero:incomingHero={},data={},mode='play',onReroll,onEdit,onWorkingChange,onToggleEdit,onNewHero,onNew,onAddToCrew,onAdd,onBack,onHome,onImportMarkdown}){
  const [hero,setHero]=useState(()=>structuredClone(incomingHero)),[pdfBusy,setPdfBusy]=useState(false),[diceOpen,setDiceOpen]=useState(false),[dicePreset,setDicePreset]=useState(null)
  const markdownInput=useRef(null)
  useEffect(()=>setHero(structuredClone(incomingHero)),[incomingHero])
  const editing=mode==='edit', personal=hero.personal||{},attrs=hero.attributes||{},skills=hero.skills||{},feats=hero.feats||[],featGroups=groupFeatIds(hero.feats),guns=hero.gear?.guns||[],items=hero.gear?.items||[]
  const itemWeapons=items.map((item,index)=>({item,index,type:savedWeaponType(item,data),collection:'items'})).filter(entry=>entry.type),gearItems=items.map((item,index)=>({item,index})).filter(({item})=>!savedWeaponType(item,data)),weapons=[...guns.map((item,index)=>({item,index,type:'ranged',collection:'guns'})),...itemWeapons]
  const roleBase=record(data,'roles',hero.role),role=useMemo(()=>(roleBase.extraTrope||roleBase.doubleTrope)&&hero.roleTrope?`${nameOf(data,'tropes',hero.roleTrope)} ${roleBase.name.replace(/^The /,'')}`:nameOf(data,'roles',hero.role),[data,hero.role,hero.roleTrope]),trope=useMemo(()=>roleBase.actsAsTrope?nameOf(data,'roles',hero.role):nameOf(data,'tropes',hero.trope),[data,hero.role,hero.trope])
  const roleDescription=catalogDescription(roleBase),tropeBase=roleBase.actsAsTrope?roleBase:record(data,'tropes',hero.trope),tropeDescription=catalogDescription(tropeBase),jobDescription=describeJob(personal.job)
  const update=(path,value)=>{const next=structuredClone(hero),parts=path.split('.');let parent=next;for(const part of parts.slice(0,-1)){if(parent[part]==null)parent[part]={};parent=parent[part]}parent[parts.at(-1)]=typeof value==='function'?value(parent[parts.at(-1)]):value;setHero(next);onWorkingChange?.(next)}
  const roleOptions=Object.entries(data.roles?.roles||{}).map(([id,item])=>({id,name:item.name,source:item.packName||'Corebook'})).sort((a,b)=>a.name.localeCompare(b.name,undefined,{sensitivity:'base',numeric:true})),tropeOptions=Object.entries(availableTropes(data.tropes?.tropes,roleBase)).map(([id,item])=>({id,name:item.name,source:item.packName||'Corebook'}))
  const roleRecord=roleBase,tropeRecord=record(data,'tropes',hero.trope),roleTropeRecord=record(data,'tropes',hero.roleTrope),allowedFeats=[...new Set([...(roleRecord.feats||[]),...(roleTropeRecord.feats||[]),...(tropeRecord.feats||[]),...(roleRecord.extraFeatPool==='all'?Object.keys(data.feats?.feats||{}):[]),...feats.filter(id=>id==='too_young_to_die')])]
  const openDice=(preset=null)=>{setDicePreset(preset);setDiceOpen(true)}
  const addWeapon=id=>{const item=structuredClone(data.gear?.weapons?.[id]||data.gear?.gear?.[id]);if(!item)return;if(isRangedWeapon(item))update('gear.guns',[...guns,{id,...item,...(usesMags(item)?{mags:2}:{})}]);else update('gear.items',[...items,{id,...item,bag:false}])}
  const addItem=id=>{const item=structuredClone(data.gear?.items?.[id]||data.gear?.gear?.[id]);if(item)update('gear.items',[...items,{id,...item,bag:false}])}
  const setRide=id=>{const item=id&&structuredClone(data.gear?.rides?.[id]||data.gear?.gear?.[id]);update('gear.ride',item?{id,...item,shields:0,shields2:0}:null)}
  async function exportPdf(){setPdfBusy(true);try{const bytes=await drawHeroSheet(hero,data);if(typeof window==='undefined')return;const url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'})),link=document.createElement('a');link.href=url;link.download=`${display(personal.name,'hero').replace(/[^a-z0-9]+/gi,'-').toLowerCase()||'hero'}-sheet.pdf`;link.click();setTimeout(()=>URL.revokeObjectURL(url),0)}finally{setPdfBusy(false)}}
  function exportMarkdown(){if(typeof window==='undefined')return;const url=URL.createObjectURL(new Blob([heroMarkdown(hero,data)],{type:'text/markdown;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=`${display(personal.name,'hero').replace(/[^a-z0-9]+/gi,'-').toLowerCase()||'hero'}-character.md`;link.click();setTimeout(()=>URL.revokeObjectURL(url),0)}
  async function copyLink(){const link=`${typeof window!=='undefined'?window.location.origin+window.location.pathname:''}#h=${encodedHero(hero)}`;if(typeof navigator!=='undefined'&&navigator.clipboard)await navigator.clipboard.writeText(link)}
  const reroll=editing?onReroll:null
  return <main style={{...styles.page,display:'grid',gap:theme.space.md}}>
    <header style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><Banner as="div" style={{display:'inline-block'}}>Hero sheet</Banner><h1 style={{...styles.display,fontSize:'clamp(30px, 6vw, 52px)',lineHeight:1,margin:'10px 0 0'}}><EditValue value={personal.name} field="personal.name" editable={editing} onEdit={onEdit} onReroll={reroll}/></h1></div><div style={{display:'flex',flexWrap:'wrap',gap:8}}>{(onHome||onBack)&&<Button onClick={onHome||onBack}>Home</Button>}<Button onClick={()=>openDice()} primary>Roll dice</Button><Button onClick={exportPdf} disabled={pdfBusy}>{pdfBusy?'Making PDF…':'Export PDF'}</Button><Button onClick={exportMarkdown}>Download Markdown</Button>{onImportMarkdown&&<><input ref={markdownInput} className="visually-hidden" type="file" accept=".md,text/markdown,text/plain" onChange={event=>{const file=event.target.files?.[0];if(file)onImportMarkdown(file);event.target.value=''}}/><Button onClick={()=>markdownInput.current?.click()}>Upload Markdown</Button></>}<Button onClick={copyLink}>Copy link</Button>{onToggleEdit&&<Button onClick={onToggleEdit} primary={editing}>{editing?'Finish editing':'Edit hero'}</Button>}</div></header>
    <DiceRoller attributes={attrs} skills={skills} conditions={hero.conditions||[]} open={diceOpen} preset={dicePreset} onClose={()=>setDiceOpen(false)}/>
    {editing&&<aside className="edit-notice"><strong>Editing hero</strong><span>Change identity, Role, Trope, Feats, Weapons, Gear, and Ride. Rules-derived dots rebuild when Role, Trope, or Age changes.</span></aside>}
    <Section title="Hero"><div style={{display:'grid',gap:theme.space.md}}><div className="identity-grid" style={{display:'grid',gridTemplateColumns:'repeat(auto-fit, minmax(min(100%, 220px), 1fr))',gap:theme.space.md}}><Field label="Role">{editing?<EditSelect value={hero.role} field="role" options={roleOptions} onEdit={onEdit} onReroll={reroll}/>:<EditValue value={role} field="role"/>}<IdentityDescription>{roleDescription}</IdentityDescription></Field><Field label="Trope">{editing?<EditSelect value={hero.trope} field="trope" options={tropeOptions} onEdit={onEdit} onReroll={reroll}/>:<EditValue value={trope} field="trope"/>}<IdentityDescription>{tropeDescription}</IdentityDescription></Field><Field label="Job"><EditValue value={personal.job} field="personal.job" editable={editing} onEdit={onEdit} onReroll={reroll}/><IdentityDescription>{jobDescription}</IdentityDescription></Field><Field label="Age">{editing?<EditSelect value={personal.age} field="personal.age" options={['Young','Adult','Old']} onEdit={onEdit} onReroll={reroll}/>:<EditValue value={personal.age} field="personal.age"/>}<IdentityDescription>{AGE_DESCRIPTIONS[personal.age]||`${display(personal.age,'Unknown age')} Hero.`}</IdentityDescription></Field>{[['Catchphrase','catchphrase'],['Flaw','flaw']].map(([label,key])=><Field key={key} label={label} style={{gridColumn:'span 2'}}><EditValue value={personal[key]} field={`personal.${key}`} editable={editing} onEdit={onEdit} onReroll={reroll}/></Field>)}</div>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit, minmax(155px, 1fr))',gap:8}}>{Object.entries(ATTRIBUTE_SKILLS).map(([attribute,names])=><div key={attribute} className="attribute-group" style={{borderTop:`3px solid ${theme.colors.red}`,padding:'8px 5px'}}><div className="attribute-score" style={{...styles.display,display:'flex',justifyContent:'space-between',alignItems:'center',fontSize:14}}><span>{attribute}</span><Dots value={attrs[attribute]} max={3} label={attribute} className="attribute-dots"/></div>{names.map(skill=><div className="skill-score" key={skill} style={{display:'flex',justifyContent:'space-between',alignItems:'center',fontSize:12,paddingTop:6}}><span>{skill.replace(/_/g,' ')}</span><Dots value={skills[skill]} max={3} label={skill} className="skill-dots"/></div>)}</div>)}</div></div></Section>
    <Section title="Feats"><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit, minmax(190px, 1fr))',gap:theme.space.md}}>{Array.from({length:Math.max(3,featGroups.length)},(_,groupIndex)=>{const group=featGroups[groupIndex],feat=group?.id,count=group?.count||0,index=feat?feats.indexOf(feat):groupIndex,item=feat?record(data,'feats',feat):null;return <article key={feat||`empty-${groupIndex}`} style={{minHeight:58,borderBottom:`1px solid ${theme.colors.line}`}}>{editing&&feat&&feat!=='too_young_to_die'?<div className="feat-editor-row"><select className="feat-editor" aria-label={`Edit feat ${groupIndex+1}`} value={feat} onChange={event=>{const id=event.target.value,record=data.feats.feats[id]||{},otherCount=feats.filter((value,other)=>other!==index&&value===id).length,limit=record.repeatable?(record.maxRanks||feats.length):1;if(otherCount<limit)update(`feats.${index}`,id)}}>{allowedFeats.map(id=>{const record=data.feats.feats[id]||{},otherCount=feats.filter((value,other)=>other!==index&&value===id).length,limit=record.repeatable?(record.maxRanks||feats.length):1;return <option key={id} value={id} disabled={otherCount>=limit}>{nameOf(data,'feats',id)}{record.repeatable?' · repeatable':''}</option>})}</select>{count>1&&<strong className="feat-rank">×{count}</strong>}</div>:<strong style={{display:'block',fontFamily:theme.fonts.display,textTransform:'uppercase'}}>{feat?<>{display(item.name,display(feat))}{count>1&&` (×${count})`}</>:'Empty slot'}</strong>}<small style={{color:theme.colors.muted,lineHeight:1.35}}>{feat?display(item.summary,''):'—'}</small></article>})}</div></Section>
    {hero.superpower&&<Section title="Superpower"><strong>{nameOf(data,'superpowers',hero.superpower)}</strong><p>{display(record(data,'superpowers',hero.superpower).summary,'')}</p></Section>}
    <Section title="Resources"><div className="resource-strip" style={{display:'flex',flexWrap:'wrap',gap:theme.space.md}}><Field label="Grit used" className="resource-meter resource-grit" style={{flex:'0 0 308px'}}><Tracker value={hero.resources?.gritUsed||0} max={12} label="Grit" variant="grit" onChange={value=>update('resources.gritUsed',value)}/></Field>{hero.superpower?<Field label="Power" className="resource-meter" style={resourceField}><Tracker value={hero.resources?.power} max={6} label="Power" onChange={value=>update('resources.power',value)}/></Field>:<Field label="Adrenaline" className="resource-meter" style={resourceField}><Tracker value={hero.resources?.adrenaline} max={6} label="Adrenaline" variant="adrenaline" onChange={value=>update('resources.adrenaline',value)}/></Field>}<Field label="Spotlight" className="resource-meter" style={resourceField}><Tracker value={hero.resources?.spotlight} max={3} label="Spotlight" variant="spotlight" onChange={value=>update('resources.spotlight',value)}/></Field><Field label="Cash" className="resource-meter" style={resourceField}><Tracker value={hero.resources?.cash} max={5} label="Cash" variant="cash" onChange={value=>update('resources.cash',value)}/></Field><Field label="Death Roulette" className="resource-meter resource-roulette" style={resourceField}><Tracker value={hero.resources?.lethalBullets} max={6} label="Death Roulette" variant="roulette" onChange={value=>update('resources.lethalBullets',value)}/></Field></div></Section>
    <Section title="Conditions & Notes"><div style={{display:'grid',gap:theme.space.md}}><Field label="You Look / Conditions"><ConditionTracker value={hero.conditions||[]} onChange={value=>update('conditions',value)}/></Field><div className="form-grid"><label>Current mission<textarea value={hero.mission||''} onChange={event=>update('mission',event.target.value)}/></label><label>Experiences<textarea value={(hero.experiences||[]).join('\n')} onChange={event=>update('experiences',event.target.value.split('\n').filter(Boolean))} placeholder="One per line"/></label></div></div></Section>
    <section className="sheet-lower" style={{display:'grid',gridTemplateColumns:'minmax(0, 1.5fr) minmax(180px, .8fr) minmax(160px, .7fr)',gap:theme.space.md}}><Section title="Weapons"><InventoryAdder label="Add weapon" values={data.gear?.weapons||data.gear?.guns} onAdd={addWeapon}/><div className="table-scroll"><table style={{borderCollapse:'collapse',fontSize:12,minWidth:470,width:'100%'}}><thead><tr>{['Name','Melee','Close','Medium','Long','Mags',...(editing?['']:[])].map((header,index)=><th key={`${header}-${index}`} style={tableHead}>{header}</th>)}</tr></thead><tbody>{Array.from({length:Math.max(3,weapons.length)},(_,index)=>{const entry=weapons[index],weapon=entry?.item,isMelee=entry?.type==='melee',weaponName=weapon&&display(weapon.name,nameOf(data,'gear',weapon)),abstractRanged=weapon&&!isMelee&&!weapon.range;return <tr key={`${weapon?.id||'empty'}-${entry?.type||'none'}-${index}`}><td style={tableCell}>{weaponName||'—'}</td>{RANGES.map(range=><td style={tableCell} key={range}>{weapon&&(isMelee&&range==='melee'?<button type="button" className="weapon-roll" aria-label={`Roll ${weaponName} with Brawn + Fight`} onClick={()=>openDice({label:weaponName,attribute:'brawn',skill:'fight',modifier:0})}>Fight</button>:abstractRanged&&range==='melee'?<button type="button" className="weapon-roll" aria-label={`Roll ${weaponName} with Nerves + Shoot`} onClick={()=>openDice({label:weaponName,attribute:'nerves',skill:'shoot',modifier:weaponModifier(weapon)})}>Shoot{weaponModifier(weapon)?` +${weaponModifier(weapon)}`:''}</button>:!isMelee&&!abstractRanged?<RangeRoll weapon={weapon} name={weaponName} range={range} onRoll={openDice}/>:display(null,'—'))}</td>)}<td style={tableCell}>{weapon&&!isMelee&&usesMags(weapon)?<Tracker value={weapon.mags} max={3} label={`${weapon.name} Mags`} onChange={value=>update(`gear.${entry.collection}.${entry.index}.mags`,value)}/>:weapon?'—':null}</td>{editing&&<td style={tableCell}>{weapon&&<button className="remove-control" aria-label={`Remove ${weapon.name}`} onClick={()=>entry.collection==='guns'?update('gear.guns',guns.filter((_,itemIndex)=>itemIndex!==entry.index)):update('gear.items',items.filter((_,itemIndex)=>itemIndex!==entry.index))}>×</button>}</td>}</tr>})}</tbody></table></div><small className="scroll-hint">Tap a range modifier or attack name to roll · swipe to see Mags →</small></Section>
      <Section title="Gear"><InventoryAdder label="Add gear" values={data.gear?.items} onAdd={addItem}/> {Array.from({length:Math.max(5,gearItems.length)},(_,index)=>{const entry=gearItems[index],item=entry?.item;return <div key={`${item?.id||'empty'}-${index}`} className="inventory-row"><span>{item?display(item.name,nameOf(data,'gear',item)):'—'}</span><span>{item&&<Tracker value={item.bag?1:0} max={1} label={`${item.name} bag`} onChange={value=>update(`gear.items.${entry.index}.bag`,!!value)}/>} {editing&&item&&<button className="remove-control" aria-label={`Remove ${item.name}`} onClick={()=>update('gear.items',items.filter((_,itemIndex)=>itemIndex!==entry.index))}>×</button>}</span></div>})}<label style={{display:'grid',gap:4,color:theme.colors.muted,fontSize:11,paddingTop:8}}>Storage<textarea value={(hero.gear?.storage||[]).join('\n')} onChange={event=>update('gear.storage',event.target.value.split('\n').filter(Boolean))}/></label></Section>
      <Section title="Ride"><label className="ride-picker">Choose ride<select value={hero.gear?.ride?.id||''} onChange={event=>setRide(event.target.value)}><option value="">No ride</option><CatalogOptions values={data.gear?.rides}/></select></label><strong style={{display:'block',fontFamily:theme.fonts.display,textTransform:'uppercase'}}>{display(hero.gear?.ride?.name)}</strong><p style={{color:theme.colors.muted,fontSize:12}}>Speed: {display(hero.gear?.ride?.speed)}</p>{hero.gear?.ride&&<div style={{fontSize:12}}>Shields <Tracker value={hero.gear.ride.shields||0} max={3} label="Ride shields" onChange={value=>update('gear.ride.shields',value)}/></div>}<p style={{color:theme.colors.muted,fontSize:11}}>Type: {display(hero.gear?.ride?.types?.join?.(', '),display(hero.gear?.ride?.type))}</p></Section></section>
    <div style={{display:'flex',justifyContent:'flex-end',flexWrap:'wrap',gap:8}}>{(onNewHero||onNew)&&<Button onClick={onNewHero||onNew}>New hero</Button>}{(onAddToCrew||onAdd)&&<Button onClick={onAddToCrew||onAdd} primary>Add to crew</Button>}</div>
  </main>
}
function ConditionTracker({value,onChange}){return <div className="condition-grid">{CONDITIONS.map(condition=>{const checked=value.includes(condition);return <button type="button" key={condition} aria-pressed={checked} className={`condition ${checked?'is-checked':''}`} onClick={()=>onChange(checked?value.filter(x=>x!==condition):[...value,condition])}><span aria-hidden="true">{checked?'✓':''}</span><span className="condition-copy"><b>{condition}</b><small>{CONDITION_EFFECTS[condition].text}</small></span></button>})}</div>}
function CatalogOptions({values={}}){const groups=groupBy(Object.entries(values),([,item])=>item.packName||'Corebook');return Object.entries(groups).map(([source,entries])=><optgroup key={source} label={source}>{entries.map(([id,item])=><option key={id} value={id}>{item.name}</option>)}</optgroup>)}
function InventoryAdder({label,values={},onAdd}){const [value,setValue]=useState('');return <div className="inventory-adder"><select aria-label={label} value={value} onChange={event=>setValue(event.target.value)}><option value="">{label}…</option><CatalogOptions values={values}/></select><button type="button" disabled={!value} onClick={()=>{onAdd(value);setValue('')}}>Add</button></div>}
function RangeRoll({weapon,name,range,onRoll}){const value=display(weapon.range?.[range],'—'),disabled=value.toUpperCase()==='X'||value==='—',modifier=Number.parseInt(value,10)||0,gamble=/G/i.test(value);return <button type="button" className="weapon-roll" disabled={disabled} aria-label={disabled?`${name} cannot attack at ${range} range`:`Roll ${name} at ${range} range (${value})`} onClick={()=>onRoll({label:`${name} · ${range}${gamble?' · Gamble':''}`,attribute:'nerves',skill:'shoot',modifier})}>{value}</button>}
function DiceRoller({attributes,skills,conditions=[],open,onClose,preset}){
  const attributeNames=Object.keys(ATTRIBUTE_SKILLS),skillNames=Object.values(ATTRIBUTE_SKILLS).flat()
  const [attribute,setAttribute]=useState(attributeNames[0]),[skill,setSkill]=useState(skillNames[0]),[modifier,setModifier]=useState(0),[difficulty,setDifficulty]=useState(3),[history,setHistory]=useState([])
  useEffect(()=>{if(!open)return;setAttribute(preset?.attribute||attributeNames[0]);setSkill(preset?.skill||skillNames[0]);setModifier(preset?.modifier||0);setHistory([])},[open,preset])
  useEffect(()=>{if(!open||typeof window==='undefined')return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const close=event=>{if(event.key==='Escape')onClose()};window.addEventListener('keydown',close);return()=>{document.body.style.overflow=previous;window.removeEventListener('keydown',close)}},[open,onClose])
  const activeConditions=conditions.filter(condition=>{const affected=CONDITION_EFFECTS[condition]?.attribute;return affected==='*'||affected===attribute}),conditionModifier=conditionPenalty(activeConditions,attribute),totalModifier=modifier+conditionModifier
  const pool=Math.max(2,Math.min(9,Number(attributes[attribute]||0)+Number(skills[skill]||0)+totalModifier))
  const successChance=actionSuccessProbability(pool,difficulty)
  const roll=()=>setHistory(current=>[{...rollAction({attribute:attributes[attribute],skill:skills[skill],modifier:totalModifier,difficulty}),attribute,skill,modifier:totalModifier,id:`${Date.now()}-${Math.random()}`},...current].slice(0,5))
  const latest=history[0],matched=new Set(latest?.combinations.map(item=>item.face)||[])
  return <div className="dice-modal-backdrop" hidden={!open} onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><div className="dice-modal" role="dialog" aria-modal="true" aria-label="Dice roller"><button type="button" className="dice-modal-close" aria-label="Close dice roller" onClick={onClose} autoFocus>×</button><Section title={preset?.label?`Roll · ${preset.label}`:'Action Roll'}><div className="dice-controls"><label>Attribute<select aria-label="Roll attribute" value={attribute} onChange={event=>setAttribute(event.target.value)}>{attributeNames.map(name=><option key={name} value={name}>{name} · {attributes[name]||0}</option>)}</select></label><span className="dice-plus">+</span><label>Skill<select aria-label="Roll skill" value={skill} onChange={event=>setSkill(event.target.value)}>{skillNames.map(name=><option key={name} value={name}>{name.replace(/_/g,' ')} · {skills[name]||0}</option>)}</select></label><label>Modifier<select aria-label="Roll modifier" value={modifier} onChange={event=>setModifier(Number(event.target.value))}>{[-3,-2,-1,0,1,2,3].map(value=><option key={value} value={value}>{value>0?`+${value}`:value}</option>)}</select></label><label>Difficulty<select aria-label="Roll difficulty" value={difficulty} onChange={event=>setDifficulty(Number(event.target.value))}>{DIFFICULTIES.map(level=><option key={level.value} value={level.value}>{level.label}</option>)}</select></label><button type="button" className="dice-roll-button" onClick={roll}>Roll {pool} dice</button></div>{activeConditions.length>0&&<small className="dice-condition-penalty">Conditions {conditionModifier}: {activeConditions.join(' + ')}</small>}<div className="dice-probability" aria-live="polite"><span>Success chance</span><strong>{(successChance*100).toFixed(successChance<.1?1:0)}%</strong><small>{pool} dice vs {DIFFICULTIES.find(level=>level.value===difficulty)?.label}</small></div>{latest&&<div className={`dice-result ${latest.passed?'is-success':'is-failure'}`} aria-live="polite"><div><strong>{latest.passed?'Success':'Failure'} · {latest.summary}</strong><small>{latest.attribute.replace(/_/g,' ')} + {latest.skill.replace(/_/g,' ')}{latest.modifier?` ${latest.modifier>0?'+':''}${latest.modifier}`:''} · {latest.pool} dice vs {DIFFICULTIES.find(level=>level.value===latest.difficulty)?.label}</small></div><div className="dice-tray" aria-label={`Dice: ${latest.dice.join(', ')}`}>{latest.dice.map((die,index)=><span key={`${latest.id}-${index}`} className={matched.has(die)?'is-match':''}>{die}</span>)}</div></div>}{history.length>1&&<details className="dice-history"><summary>Recent rolls</summary>{history.slice(1).map(result=><div key={result.id}><span>{result.attribute} + {result.skill}</span><strong>{result.dice.join(' · ')} — {result.summary}</strong></div>)}</details>}</Section></div></div>
}
function Field({label,children,style,className=''}){return <div className={className} style={{display:'grid',gap:5,minWidth:0,...style}}><span style={{...styles.display,color:theme.colors.muted,fontSize:11}}>{label}</span>{children}</div>}
function IdentityDescription({children}){return <small style={{color:theme.colors.muted,fontSize:11,lineHeight:1.3}}>{children}</small>}
const tableHead={borderBottom:`1px solid ${theme.colors.line}`,color:theme.colors.muted,fontFamily:theme.fonts.display,fontSize:10,fontWeight:400,padding:'4px',textAlign:'left',textTransform:'uppercase'},tableCell={borderBottom:`1px solid ${theme.colors.line}`,padding:'6px 4px',textAlign:'left',whiteSpace:'nowrap'}
const resourceField={flex:'0 0 auto'}
