import React,{useEffect,useMemo,useState} from 'react'
import drawHeroSheet from '../../pdf/heroSheet.js'
import {Banner,Button,Dots,Section,Tracker} from '../components/index.jsx'
import {styles,theme} from '../theme.js'

const ATTRIBUTE_SKILLS={brawn:['endure','fight','force','stunt'],nerves:['cool','drive','shoot','survival'],smooth:['flirt','leadership','speech','style'],focus:['detect','fix','heal','know'],crime:['awareness','dexterity','stealth','streetwise']}
const CONDITIONS=['Hurt','Nervous','Like a Fool','Distracted','Scared','Tired','Broken']
const display=(value,fallback='—')=>value==null||value===''?fallback:typeof value==='string'||typeof value==='number'?String(value):value.name||value.id||fallback
const groupBy=(values,key)=>values.reduce((groups,value)=>{const group=key(value);(groups[group]??=[]).push(value);return groups},{})
function record(data,collection,value){const id=typeof value==='string'?value:value?.id,group=data?.[collection]||{},source=group[collection]||group.gear||group;return source[id]||value||{}}
const nameOf=(data,collection,value)=>display(record(data,collection,value).name,display(value).replace(/[_-]+/g,' '))
function encodedHero(hero){if(typeof btoa!=='function')return '';return btoa(unescape(encodeURIComponent(JSON.stringify(hero)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}

function EditValue({value,field,editable,onEdit,onReroll}){const [draft,setDraft]=useState(()=>display(value,''));useEffect(()=>setDraft(display(value,'')),[value]);if(editable)return <span className="inline-editor"><input value={draft} aria-label={`Edit ${field}`} onChange={event=>setDraft(event.target.value)} onBlur={()=>onEdit?.(field,draft)} onKeyDown={event=>{if(event.key==='Enter')event.currentTarget.blur();if(event.key==='Escape'){setDraft(display(value,''));event.currentTarget.blur()}}}/>{onReroll&&<button type="button" onClick={()=>onReroll(field)} aria-label={`Reroll ${field}`} style={iconButton}>↻</button>}</span>;return <span style={{display:'inline-flex',alignItems:'center',gap:5,minWidth:0}}><span style={{overflow:'hidden',textOverflow:'ellipsis'}}>{display(value)}</span>{onReroll&&<button type="button" onClick={()=>onReroll(field)} aria-label={`Reroll ${field}`} style={iconButton}>↻</button>}</span>}
function EditSelect({value,field,options,onEdit,onReroll}){const groups=groupBy(options,option=>option.source||'');return <span className="inline-editor"><select value={value||''} aria-label={`Edit ${field}`} onChange={event=>onEdit?.(field,event.target.value)}>{Object.entries(groups).map(([source,values])=>source?<optgroup key={source} label={source}>{values.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</optgroup>:values.map(option=><option key={option.id||option} value={option.id||option}>{option.name||option}</option>))}</select>{onReroll&&<button type="button" onClick={()=>onReroll(field)} aria-label={`Reroll ${field}`} style={iconButton}>↻</button>}</span>}
const iconButton={appearance:'none',background:'transparent',border:0,color:theme.colors.red,cursor:'pointer',fontSize:17,lineHeight:1,padding:0}

export default function HeroSheet({hero:incomingHero={},data={},mode='play',onReroll,onEdit,onWorkingChange,onToggleEdit,onNewHero,onNew,onAddToCrew,onAdd,onBack,onHome}){
  const [hero,setHero]=useState(()=>structuredClone(incomingHero)),[pdfBusy,setPdfBusy]=useState(false)
  useEffect(()=>setHero(structuredClone(incomingHero)),[incomingHero])
  const editing=mode==='edit', personal=hero.personal||{},attrs=hero.attributes||{},skills=hero.skills||{},feats=hero.feats||[],guns=hero.gear?.guns||[],items=hero.gear?.items||[]
  const role=useMemo(()=>nameOf(data,'roles',hero.role),[data,hero.role]),trope=useMemo(()=>nameOf(data,'tropes',hero.trope),[data,hero.trope])
  const update=(path,value)=>{const next=structuredClone(hero),parts=path.split('.');let parent=next;for(const part of parts.slice(0,-1)){if(parent[part]==null)parent[part]={};parent=parent[part]}parent[parts.at(-1)]=typeof value==='function'?value(parent[parts.at(-1)]):value;setHero(next);onWorkingChange?.(next)}
  const roleOptions=Object.entries(data.roles?.roles||{}).map(([id,item])=>({id,name:item.name,source:item.packName||'Corebook'})),tropeOptions=Object.entries(data.tropes?.tropes||{}).map(([id,item])=>({id,name:item.name,source:item.packName||'Corebook'}))
  const roleRecord=record(data,'roles',hero.role),tropeRecord=record(data,'tropes',hero.trope),allowedFeats=[...new Set([...(roleRecord.feats||[]),...(tropeRecord.feats||[]),...feats.filter(id=>id==='too_young_to_die')])]
  const addGun=id=>{const item=structuredClone(data.gear?.guns?.[id]||data.gear?.gear?.[id]);if(item)update('gear.guns',[...guns,{id,...item,mags:2}])}
  const addItem=id=>{const item=structuredClone(data.gear?.items?.[id]||data.gear?.gear?.[id]);if(item)update('gear.items',[...items,{id,...item,bag:false}])}
  const setRide=id=>{const item=id&&structuredClone(data.gear?.rides?.[id]||data.gear?.gear?.[id]);update('gear.ride',item?{id,...item,shields:0,shields2:0}:null)}
  async function exportPdf(){setPdfBusy(true);try{const bytes=await drawHeroSheet(hero,data);if(typeof window==='undefined')return;const url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'})),link=document.createElement('a');link.href=url;link.download=`${display(personal.name,'hero').replace(/[^a-z0-9]+/gi,'-').toLowerCase()||'hero'}-sheet.pdf`;link.click();setTimeout(()=>URL.revokeObjectURL(url),0)}finally{setPdfBusy(false)}}
  async function copyLink(){const link=`${typeof window!=='undefined'?window.location.origin+window.location.pathname:''}#h=${encodedHero(hero)}`;if(typeof navigator!=='undefined'&&navigator.clipboard)await navigator.clipboard.writeText(link)}
  const reroll=editing?onReroll:null
  return <main style={{...styles.page,display:'grid',gap:theme.space.md}}>
    <header style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><Banner as="div" style={{display:'inline-block'}}>Hero sheet</Banner><h1 style={{...styles.display,fontSize:'clamp(30px, 6vw, 52px)',lineHeight:1,margin:'10px 0 0'}}><EditValue value={personal.name} field="personal.name" editable={editing} onEdit={onEdit} onReroll={reroll}/></h1></div><div style={{display:'flex',flexWrap:'wrap',gap:8}}>{(onHome||onBack)&&<Button onClick={onHome||onBack}>Home</Button>}<Button onClick={exportPdf} disabled={pdfBusy} primary>{pdfBusy?'Making PDF…':'Export PDF'}</Button><Button onClick={copyLink}>Copy link</Button>{onToggleEdit&&<Button onClick={onToggleEdit} primary={editing}>{editing?'Finish editing':'Edit hero'}</Button>}</div></header>
    {editing&&<aside className="edit-notice"><strong>Editing hero</strong><span>Change identity, Role, Trope, Feats, Guns, Gear, and Ride. Rules-derived dots rebuild when Role, Trope, or Age changes.</span></aside>}
    <section style={{...styles.card,display:'grid',gap:theme.space.md}}><div className="identity-grid" style={{display:'grid',gridTemplateColumns:'repeat(auto-fit, minmax(min(100%, 220px), 1fr))',gap:theme.space.md}}><Field label="Role">{editing?<EditSelect value={hero.role} field="role" options={roleOptions} onEdit={onEdit} onReroll={reroll}/>:<EditValue value={role} field="role"/>}</Field><Field label="Trope">{editing?<EditSelect value={hero.trope} field="trope" options={tropeOptions} onEdit={onEdit} onReroll={reroll}/>:<EditValue value={trope} field="trope"/>}</Field>{[['Job','job'],['Age','age'],['Catchphrase','catchphrase'],['Flaw','flaw']].map(([label,key])=><Field key={key} label={label} style={key==='catchphrase'||key==='flaw'?{gridColumn:'span 2'}:{}}>{editing&&key==='age'?<EditSelect value={personal.age} field="personal.age" options={['Young','Adult','Old']} onEdit={onEdit} onReroll={reroll}/>:<EditValue value={personal[key]} field={`personal.${key}`} editable={editing} onEdit={onEdit} onReroll={reroll}/>}</Field>)}</div>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit, minmax(155px, 1fr))',gap:8}}>{Object.entries(ATTRIBUTE_SKILLS).map(([attribute,names])=><div key={attribute} style={{borderTop:`3px solid ${theme.colors.red}`,padding:'8px 5px'}}><div style={{...styles.display,display:'flex',justifyContent:'space-between',alignItems:'center',fontSize:14}}><span>{attribute}</span><Dots value={attrs[attribute]} max={3} label={attribute}/></div>{names.map(skill=><div key={skill} style={{display:'flex',justifyContent:'space-between',alignItems:'center',fontSize:12,paddingTop:6}}><span>{skill.replace(/_/g,' ')}</span><Dots value={skills[skill]} max={3} label={skill}/></div>)}</div>)}</div></section>
    <Section title="Feats"><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit, minmax(190px, 1fr))',gap:theme.space.md}}>{Array.from({length:Math.max(3,feats.length)},(_,index)=>{const feat=feats[index],item=feat?record(data,'feats',feat):null;return <article key={`${feat||'empty'}-${index}`} style={{minHeight:58,borderBottom:`1px solid ${theme.colors.line}`}}>{editing&&feat&&feat!=='too_young_to_die'?<select className="feat-editor" aria-label={`Edit feat ${index+1}`} value={feat} onChange={event=>{const id=event.target.value,record=data.feats.feats[id]||{},otherCount=feats.filter((value,other)=>other!==index&&value===id).length,limit=record.repeatable?(record.maxRanks||feats.length):1;if(otherCount<limit)update(`feats.${index}`,id)}}>{allowedFeats.map(id=>{const record=data.feats.feats[id]||{},otherCount=feats.filter((value,other)=>other!==index&&value===id).length,limit=record.repeatable?(record.maxRanks||feats.length):1;return <option key={id} value={id} disabled={otherCount>=limit}>{nameOf(data,'feats',id)}{record.repeatable?' · repeatable':''}</option>})}</select>:<strong style={{display:'block',fontFamily:theme.fonts.display,textTransform:'uppercase'}}>{feat?display(item.name,display(feat)):'Empty slot'}</strong>}<small style={{color:theme.colors.muted,lineHeight:1.35}}>{feat?display(item.summary,''):'—'}</small></article>})}</div></Section>
    {hero.superpower&&<Section title="Superpower"><strong>{nameOf(data,'superpowers',hero.superpower)}</strong><p>{display(record(data,'superpowers',hero.superpower).summary,'')}</p></Section>}
    <section style={{...styles.card,display:'flex',flexWrap:'wrap',alignItems:'flex-start',gap:theme.space.md}}><Field label="Grit used" style={{flex:'0 0 284px'}}><Tracker value={hero.resources?.gritUsed||0} max={12} label="Grit" onChange={value=>update('resources.gritUsed',value)}/></Field>{hero.superpower?<Field label="Power" style={resourceField}><Tracker value={hero.resources?.power} max={6} label="Power" onChange={value=>update('resources.power',value)}/></Field>:<Field label="Adrenaline" style={resourceField}><Tracker value={hero.resources?.adrenaline} max={6} label="Adrenaline" onChange={value=>update('resources.adrenaline',value)}/></Field>}<Field label="Spotlight" style={resourceField}><Tracker value={hero.resources?.spotlight} max={3} label="Spotlight" onChange={value=>update('resources.spotlight',value)}/></Field><Field label="Cash" style={resourceField}><Tracker value={hero.resources?.cash} max={5} label="Cash" onChange={value=>update('resources.cash',value)}/></Field><Field label="Lethal bullets" style={resourceField}><Tracker value={hero.resources?.lethalBullets} max={6} label="Lethal bullets" onChange={value=>update('resources.lethalBullets',value)}/></Field></section>
    <section style={{...styles.card,display:'grid',gap:theme.space.md}}><Field label="You Look / Conditions"><ConditionTracker value={hero.conditions||[]} onChange={value=>update('conditions',value)}/></Field><div className="form-grid"><label>Current mission<textarea value={hero.mission||''} onChange={event=>update('mission',event.target.value)}/></label><label>Experiences<textarea value={(hero.experiences||[]).join('\n')} onChange={event=>update('experiences',event.target.value.split('\n').filter(Boolean))} placeholder="One per line"/></label></div></section>
    <section className="sheet-lower" style={{display:'grid',gridTemplateColumns:'minmax(0, 1.5fr) minmax(180px, .8fr) minmax(160px, .7fr)',gap:theme.space.md}}><Section title="Guns">{editing&&<InventoryAdder label="Add gun" values={data.gear?.guns} onAdd={addGun}/>}<div className="table-scroll"><table style={{borderCollapse:'collapse',fontSize:12,minWidth:470,width:'100%'}}><thead><tr>{['Name','Melee','Close','Medium','Long','Mags',...(editing?['']:[])].map((header,index)=><th key={`${header}-${index}`} style={tableHead}>{header}</th>)}</tr></thead><tbody>{Array.from({length:Math.max(3,guns.length)},(_,index)=>{const gun=guns[index];return <tr key={`${gun?.id||'empty'}-${index}`}><td style={tableCell}>{gun?display(gun.name,nameOf(data,'gear',gun)):'—'}</td>{['melee','close','medium','long'].map(range=><td style={tableCell} key={range}>{display(gun?.range?.[range],'—')}</td>)}<td style={tableCell}>{gun&&<Tracker value={gun.mags} max={3} label={`${gun.name} Mags`} onChange={value=>update(`gear.guns.${index}.mags`,value)}/>}</td>{editing&&<td style={tableCell}>{gun&&<button className="remove-control" aria-label={`Remove ${gun.name}`} onClick={()=>update('gear.guns',guns.filter((_,itemIndex)=>itemIndex!==index))}>×</button>}</td>}</tr>})}</tbody></table></div><small className="scroll-hint">Swipe the table to see Mags →</small></Section>
      <Section title="Gear">{editing&&<InventoryAdder label="Add gear" values={data.gear?.items} onAdd={addItem}/>} {Array.from({length:Math.max(5,items.length)},(_,index)=>{const item=items[index];return <div key={`${item?.id||'empty'}-${index}`} className="inventory-row"><span>{item?display(item.name,nameOf(data,'gear',item)):'—'}</span><span>{item&&<Tracker value={item.bag?1:0} max={1} label={`${item.name} bag`} onChange={value=>update(`gear.items.${index}.bag`,!!value)}/>} {editing&&item&&<button className="remove-control" aria-label={`Remove ${item.name}`} onClick={()=>update('gear.items',items.filter((_,itemIndex)=>itemIndex!==index))}>×</button>}</span></div>})}<label style={{display:'grid',gap:4,color:theme.colors.muted,fontSize:11,paddingTop:8}}>Storage<textarea value={(hero.gear?.storage||[]).join('\n')} onChange={event=>update('gear.storage',event.target.value.split('\n').filter(Boolean))}/></label></Section>
      <Section title="Ride">{editing&&<label className="ride-picker">Choose ride<select value={hero.gear?.ride?.id||''} onChange={event=>setRide(event.target.value)}><option value="">No ride</option><CatalogOptions values={data.gear?.rides}/></select></label>}<strong style={{display:'block',fontFamily:theme.fonts.display,textTransform:'uppercase'}}>{display(hero.gear?.ride?.name)}</strong><p style={{color:theme.colors.muted,fontSize:12}}>Speed: {display(hero.gear?.ride?.speed)}</p>{hero.gear?.ride&&<div style={{fontSize:12}}>Shields <Tracker value={hero.gear.ride.shields||0} max={3} label="Ride shields" onChange={value=>update('gear.ride.shields',value)}/></div>}<p style={{color:theme.colors.muted,fontSize:11}}>Type: {display(hero.gear?.ride?.types?.join?.(', '),display(hero.gear?.ride?.type))}</p></Section></section>
    <div style={{display:'flex',justifyContent:'flex-end',flexWrap:'wrap',gap:8}}>{(onNewHero||onNew)&&<Button onClick={onNewHero||onNew}>New hero</Button>}{(onAddToCrew||onAdd)&&<Button onClick={onAddToCrew||onAdd} primary>Add to crew</Button>}</div>
  </main>
}
function ConditionTracker({value,onChange}){return <div className="condition-grid">{CONDITIONS.map(condition=>{const checked=value.includes(condition);return <button type="button" key={condition} aria-pressed={checked} className={`condition ${checked?'is-checked':''}`} onClick={()=>onChange(checked?value.filter(x=>x!==condition):[...value,condition])}><span aria-hidden="true">{checked?'✓':''}</span>{condition}</button>})}</div>}
function CatalogOptions({values={}}){const groups=groupBy(Object.entries(values),([,item])=>item.packName||'Corebook');return Object.entries(groups).map(([source,entries])=><optgroup key={source} label={source}>{entries.map(([id,item])=><option key={id} value={id}>{item.name}</option>)}</optgroup>)}
function InventoryAdder({label,values={},onAdd}){const [value,setValue]=useState('');return <div className="inventory-adder"><select aria-label={label} value={value} onChange={event=>setValue(event.target.value)}><option value="">{label}…</option><CatalogOptions values={values}/></select><button type="button" disabled={!value} onClick={()=>{onAdd(value);setValue('')}}>Add</button></div>}
function Field({label,children,style}){return <div style={{display:'grid',gap:5,minWidth:0,...style}}><span style={{...styles.display,color:theme.colors.muted,fontSize:11}}>{label}</span>{children}</div>}
const tableHead={borderBottom:`1px solid ${theme.colors.line}`,color:theme.colors.muted,fontFamily:theme.fonts.display,fontSize:10,fontWeight:400,padding:'4px',textAlign:'left',textTransform:'uppercase'},tableCell={borderBottom:`1px solid ${theme.colors.line}`,padding:'6px 4px',textAlign:'left',whiteSpace:'nowrap'}
const resourceField={flex:'0 0 auto'}
