const descriptions={
  'Acolyte':'A devoted junior member of a faith or order.',
  'Actor':'A professional performer for stage or screen.',
  'Ancient Order':'A member of an old and secretive order.',
  'Angel':'A celestial servant and divine messenger.',
  'Archeologist':'A scholar who studies ancient peoples and artifacts.',
  'Aristocrat':'A privileged member of the upper class.',
  'Athlete':'A competitor trained for physical performance.',
  'Aviator':'A pilot skilled in flying aircraft.',
  'Bandit':'An outlaw who robs travelers and settlements.',
  'Barbarian':'A fierce warrior from beyond civilized lands.',
  'Belmont':'A monster hunter from the legendary Belmont line.',
  'Biker':'A road-hardened motorcycle rider.',
  'Blacksmith':'A craftsperson who forges metal tools and weapons.',
  'Bodyguard':'A professional hired to protect others.',
  'Bouncer':'Security who keeps order at a venue.',
  'Bounty Hunter':'A tracker who captures wanted targets for payment.',
  'CIA Agent':'An American foreign-intelligence operative.',
  'Canine Unit':'A trained service dog and handler team.',
  'Captain':'An officer who commands a crew or unit.',
  'Cashier':'A worker who handles sales and payments.',
  'Convict':'A person serving or marked by a criminal sentence.',
  'Cook':'A professional who prepares meals.',
  'Courier':'A fast, reliable carrier of packages or messages.',
  'Criminal':'A professional operating outside the law.',
  'Criminal Mastermind':'A strategist who plans and controls major crimes.',
  'Demolition Expert':'A specialist in explosives and controlled destruction.',
  'Demon':'A supernatural creature from a hellish realm.',
  'Detective':'An investigator who solves crimes and mysteries.',
  'Double Agent':'A spy secretly serving two opposing sides.',
  'Employee':'An ordinary worker with an ordinary day job.',
  'Enforcer':'Muscle who secures compliance through intimidation or force.',
  'Engineer':'A technical expert who designs and builds systems.',
  'Exorcist':'A specialist who confronts and expels evil spirits.',
  'Explorer':'An adventurer who travels into unknown places.',
  'Family Associate':'A trusted affiliate of an organized-crime family.',
  'Farmer':'A worker who raises crops or livestock.',
  'Field Medic':'A medical responder trained for dangerous conditions.',
  'Fixer':'A connected problem-solver who arranges illicit services.',
  'Former Soldier':'A trained combatant no longer in active service.',
  'Fugitive':'A wanted person living on the run.',
  'Full-time Hero':'A professional protector devoted entirely to heroics.',
  'Government Agent':'An operative working for a government agency.',
  'Grave Robber':'A thief who loots graves and burial sites.',
  'Great Performer':'A celebrated master of live entertainment.',
  'Guardian':'A sworn protector of a person, place, or cause.',
  'Hacker':'A computer expert who breaks into digital systems.',
  'Heir':'The designated successor to wealth, rank, or power.',
  'Homeless':'A person surviving without stable housing.',
  'Humble Artisan':'A modest craftsperson skilled in handmade work.',
  'Hunter':'A tracker who pursues animals or other quarry.',
  'Informer':'A source who trades inside information.',
  'Intern':'A junior worker learning through practical experience.',
  'Investigator':'A professional who uncovers facts and follows evidence.',
  'Jedi':'A Force-sensitive guardian trained in the Jedi arts.',
  'KGB Spy':'A Soviet intelligence operative.',
  'Librarian':'A curator and guide to books and information.',
  'MI6 Agent':'A British foreign-intelligence operative.',
  'Marine':'An elite soldier trained for amphibious operations.',
  'Martial Arts Teacher':'An instructor in disciplined hand-to-hand combat.',
  'Mechanic':'A technician who repairs vehicles and machinery.',
  'Mercenary':'A professional soldier who fights for payment.',
  'Military Veteran':'An experienced former member of the armed forces.',
  'Musician':'A professional performer or composer of music.',
  'Musketeer':'A dashing soldier skilled with blade and musket.',
  'Netrunner':'A specialist who infiltrates dangerous digital networks.',
  'Noble':'A titled member of the ruling class.',
  'Nurse':'A medical professional who treats and cares for patients.',
  'Occult Detective':'An investigator of supernatural crimes and mysteries.',
  'Officer of the Time Police':'An agent who enforces the laws of time travel.',
  'Outlaw':'A wanted criminal living beyond the law.',
  'Patrol Officer':'A police officer assigned to protect a local area.',
  'Pilot':'A professional trained to fly aircraft.',
  'Pirate':'A seaborne outlaw who raids and steals.',
  'Poacher':'An illegal hunter of protected game.',
  'Police':'A law-enforcement officer who protects the public.',
  'Police Officer':'A law-enforcement officer who protects the public.',
  'Postal Worker':'A worker who sorts and delivers mail.',
  'Private Driver':'A professional chauffeur for private clients.',
  'Private Eye':'An independent investigator hired by private clients.',
  'Professional Gambler':'A skilled bettor who makes a living from games.',
  'Professor':'An academic who teaches and conducts research.',
  'Prophet':'A visionary who receives and proclaims divine messages.',
  'Rat':'A small, resourceful survivor of streets and shadows.',
  'Reporter':'A journalist who investigates and reports the news.',
  'Researcher':'A specialist who systematically discovers new knowledge.',
  'Salesperson':'A professional who persuades customers to buy.',
  'Sapper':'A military engineer specializing in fortifications and explosives.',
  'Saved by Natives':'An outsider adopted and taught by an isolated people.',
  'Scholar':'A learned expert devoted to study and knowledge.',
  'Sheriff':'The chief law-enforcement officer of a county or town.',
  'Ship Captain':'An officer who commands a vessel and its crew.',
  'Smuggler':'A transporter who secretly moves illegal goods or people.',
  'Soldier':'A trained member of the armed forces.',
  "Sorcerer's Assistant":'An apprentice who supports a practicing sorcerer.',
  'Street Samurai':'A heavily armed urban mercenary with a personal code.',
  'Student':'A learner pursuing formal education or training.',
  'Supervillain':'A powerful criminal with an extraordinary persona.',
  'Teenage Star':'A young celebrity working in entertainment.',
  'Terrorist':'An extremist who uses violence to pursue political aims.',
  'Thief':'A criminal skilled at stealing valuables.',
  'Time Lord':'A master traveler with deep knowledge of time.',
  'Timeline Guardian':'A protector who preserves the proper course of history.',
  'Tomb Robber':'A treasure hunter who plunders ancient burial places.',
  'Trusted Mount':'A loyal animal companion trained for travel and danger.',
  'Unemployed':'Currently without a regular occupation.',
  'University Professor':'A senior academic who teaches and conducts research.',
  'Vampire Hunter':'A specialist trained to track and destroy vampires.',
  'Veteran':'A seasoned former service member or combatant.',
  'Viking':'A Norse seafarer, raider, and warrior.',
  'Wandering Knight':'A traveling armored warrior seeking a cause.',
  'Warrior':'A trained fighter who lives by force of arms.',
  'White-collar Worker':'An office professional in business or administration.',
  'Yakuza':'A member of a Japanese organized-crime syndicate.',
}

export function describeJob(job){
  if(!job)return 'No job has been chosen yet.'
  return descriptions[job]||`A professional working as ${job.toLowerCase()}.`
}

export default describeJob
