import React from 'react'; import {describe,expect,it} from 'vitest'; import {renderToString} from 'react-dom/server'; import {gameData} from '../../src/data.js'; import {generateRandom} from '../../src/engine/hero.js'; import {makeRng} from '../../src/engine/dice.js'; import Menu from '../../src/ui/screens/Menu.jsx'; import HeroSheet from '../../src/ui/screens/HeroSheet.jsx'; import RandomHero from '../../src/ui/screens/RandomHero.jsx'; import GuidedHero,{GuidedReview} from '../../src/ui/screens/GuidedHero.jsx'; import Questionnaire from '../../src/ui/screens/Questionnaire.jsx'; import Crew from '../../src/ui/screens/Crew.jsx'; import Mission from '../../src/ui/screens/Mission.jsx'; import Oracles from '../../src/ui/screens/Oracles.jsx'
describe('screens',()=>{for(const [name,View,props] of [['menu',Menu,{}],['random',RandomHero,{data:gameData}],['guided',GuidedHero,{data:gameData}],['quiz',Questionnaire,{data:gameData}],['crew',Crew,{data:gameData}],['mission',Mission,{data:gameData}],['oracles',Oracles,{data:gameData}]])it(`renders ${name}`,()=>expect(renderToString(<View onBack={()=>{}} onSelectMode={()=>{}} onAccept={()=>{}} onRoll={()=>{}} {...props}/>).length).toBeGreaterThan(50))})
it('places Continue a character after the main toolkit tiles',()=>{const html=renderToString(<Menu onSelectMode={()=>{}} onImportMarkdown={()=>{}}/>);expect(html.indexOf('Continue a character')).toBeGreaterThan(html.indexOf('Oracles'))})
it('lists Roles alphabetically in Guided Hero',()=>{const html=renderToString(<GuidedHero data={gameData} onBack={()=>{}}/>),ace=html.indexOf('The Ace'),brain=html.indexOf('The Brain'),commando=html.indexOf('The Commando');expect(ace).toBeGreaterThan(-1);expect(ace).toBeLessThan(brain);expect(brain).toBeLessThan(commando)})
it('orders Trope before Personal Data in Guided Hero',()=>{const html=renderToString(<GuidedHero data={gameData} onBack={()=>{}} defaults={{role:'commando'}}/>);expect(html).toContain('<h1>Trope</h1>')})

describe('working hero sheet',()=>{const hero=generateRandom(makeRng(3),gameData);it('uses Home and hides rerolls during play',()=>{const html=renderToString(<HeroSheet hero={hero} data={gameData} onHome={()=>{}} onReroll={()=>{}} onImportMarkdown={()=>{}}/>);expect(html).toContain('Home');expect(html).not.toContain('Reroll personal.name');expect(html).toContain('aria-label="Grit 0 of 12"');expect(html).toContain('Bad!');expect(html).toContain('Hot!');expect(html).toContain('Suffer a Condition');expect(html).toContain('Gain 2 Adrenaline');expect(html).toContain('tracker--spotlight');expect(html).toContain('tracker--cash');expect(html).toContain('resource-roulette');expect(html).toContain('Current mission');expect(html).toContain('Download Markdown');expect(html).toContain('Upload Markdown');expect(html).toContain('attribute-score');expect(html).toContain('skill-score')});it('shows rerolls only in the editing menu',()=>{const html=renderToString(<HeroSheet hero={hero} data={gameData} mode="edit" onReroll={()=>{}}/>);expect(html).toContain('Reroll personal.name');expect(html).toContain('Reroll role')})})
it('consolidates repeated Feats on the sheet',()=>{const hero=generateRandom(makeRng(3),gameData);hero.feats=['gunslinger','gunslinger','hard_to_kill'];const html=renderToString(<HeroSheet hero={hero} data={gameData}/>);expect(html).toContain('Gunslinger<!-- --> (×2)');expect((html.match(/Gunslinger/g)||[])).toHaveLength(1)})

describe('hero editor',()=>{const hero=generateRandom(makeRng(7),gameData);it('exposes identity controls in edit mode',()=>{const html=renderToString(<HeroSheet hero={hero} data={gameData} mode="edit" onEdit={()=>{}} onWorkingChange={()=>{}}/>);expect(html).toContain('Editing hero');expect(html).toContain('aria-label="Edit role"')});it('keeps inventory controls available during play and puts dice in a popup',()=>{const html=renderToString(<HeroSheet hero={hero} data={gameData}/>);expect(html).toContain('aria-label="Add gun"');expect(html).toContain('aria-label="Add gear"');expect(html).toContain('Choose ride');expect(html).toContain('Roll dice');expect(html).toContain('role="dialog"');expect(html).toContain('dice-modal-backdrop');expect(html).toContain('hidden=""')})})
it('makes a completed guided character editable',()=>{const hero=generateRandom(makeRng(11),gameData),html=renderToString(<GuidedReview initial={hero} data={gameData} onHome={()=>{}}/>);expect(html).toContain('Edit hero')})
